import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="container mx-auto bg-black backdrop-blur-2xl h-[50px] flex justify-between items-center">
          <h1>Dummy API</h1>
          <div className="flex justify-around gap-y-4 w-1/4">
          <Link className="py-2" href="/">Home</Link>
          <Link className="py-2" href="/cart">Cart</Link>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
